from __future__ import annotations

import re
from difflib import SequenceMatcher

from app.core.ai.base import AIDriftProposal, FieldSuggestion

# Ordered (keyword, semantic_field) rules. More specific tokens come first so that
# e.g. "srcport" is matched to source.port before the broader "src" -> source.ip.
KEYWORD_RULES = [
    ("srcip", "source.ip"),
    ("sourceip", "source.ip"),
    ("sourceaddress", "source.ip"),
    ("sip", "source.ip"),
    ("src", "source.ip"),
    ("source", "source.ip"),
    ("dstip", "destination.ip"),
    ("destip", "destination.ip"),
    ("destinationaddress", "destination.ip"),
    ("dip", "destination.ip"),
    ("dst", "destination.ip"),
    ("dest", "destination.ip"),
    ("destination", "destination.ip"),
    ("srcport", "source.port"),
    ("sport", "source.port"),
    ("dstport", "destination.port"),
    ("dport", "destination.port"),
    ("srcmac", "source.mac"),
    ("dstmac", "destination.mac"),
    ("protocol", "network.protocol"),
    ("proto", "network.protocol"),
    ("decision", "network.action"),
    ("action", "network.action"),
    ("act", "network.action"),
    ("username", "identity.user"),
    ("user", "identity.user"),
    ("sessionid", "identity.session_id"),
    ("session", "identity.session_id"),
    ("hostname", "source.hostname"),
    ("host", "source.hostname"),
    ("severity", "event.severity"),
    ("sev", "event.severity"),
    ("outcome", "event.outcome"),
    ("signature", "threat.signature"),
    ("sig", "threat.signature"),
    ("category", "threat.category"),
]


def _norm(name: str) -> str:
    return re.sub(r"[^a-z0-9]", "", name.lower())


def _keyword_match(field: str) -> tuple[str, float] | None:
    nf = _norm(field)
    for keyword, semantic in KEYWORD_RULES:
        if keyword in nf:
            return semantic, 0.92
    return None


def _rename_candidate(field: str, missing: set[str], known_semantics: dict[str, str]):
    """Pair a new field with a missing known field via name similarity."""
    nf = _norm(field)
    best = None
    best_ratio = 0.0
    for missing_field in missing:
        ratio = SequenceMatcher(None, nf, _norm(missing_field)).ratio()
        if ratio > best_ratio:
            best_ratio = ratio
            best = missing_field
    if best is not None and best_ratio >= 0.55:
        semantic = known_semantics.get(best)
        if semantic:
            return semantic, round(best_ratio, 2)
    return None


class HeuristicAIProvider:
    """Deterministic, offline intelligence layer.

    Produces structured proposals using keyword semantics and name-similarity rename
    detection. Fast, predictable, and fully testable without a local LLM.
    """

    def analyze_drift(
        self,
        *,
        source: str | None,
        new_fields: set[str],
        missing_fields: set[str],
        known_semantics: dict[str, str],
        sample: str | None,
    ) -> AIDriftProposal:
        # `known_semantics` maps known source field -> semantic field (for renames).
        suggestions: list[FieldSuggestion] = []
        renamed_from: dict[str, str] = {}
        confidences: list[float] = []

        for field in sorted(new_fields):
            semantic, conf = None, 0.0
            reason = ""
            match = _keyword_match(field)
            if match:
                semantic, conf = match
                reason = f"keyword heuristic"
            else:
                rename = _rename_candidate(field, set(missing_fields), known_semantics)
                if rename:
                    semantic, conf = rename
                    reason = "name-similarity to missing field"
                    renamed_from[field] = _best_missing(field, missing_fields)
            if semantic:
                suggestions.append(
                    FieldSuggestion(field, semantic, conf, reason)
                )
                confidences.append(conf)
            else:
                suggestions.append(
                    FieldSuggestion(field, "", 0.0, "no confident match; requires review")
                )

        overall = round(sum(confidences) / len(confidences), 3) if confidences else 0.0
        explanation = (
            f"Source '{source or 'unknown'}' changed structure: "
            f"{len(new_fields)} new field(s), {len(missing_fields)} missing. "
            f"Suggestions generated by deterministic heuristic rules."
        )
        return AIDriftProposal(
            new_field_suggestions=suggestions,
            renamed_from=renamed_from,
            explanation=explanation,
            confidence=overall,
        )

    def propose_mapping(
        self,
        *,
        source: str | None,
        field_map: dict[str, object],
        sample: str | None,
    ) -> AIDriftProposal:
        """Suggest a full field -> semantic mapping for a fresh, unmapped source."""
        suggestions: list[FieldSuggestion] = []
        confidences: list[float] = []

        for field in sorted(field_map.keys()):
            match = _keyword_match(field)
            if match:
                semantic, conf = match
                suggestions.append(
                    FieldSuggestion(field, semantic, conf, "keyword heuristic")
                )
                confidences.append(conf)
            else:
                suggestions.append(
                    FieldSuggestion(field, "", 0.0, "no confident match; requires review")
                )

        overall = round(sum(confidences) / len(confidences), 3) if confidences else 0.0
        return AIDriftProposal(
            new_field_suggestions=suggestions,
            explanation=f"Suggested mapping for source '{source or 'unknown'}'.",
            confidence=overall,
        )


def _best_missing(field: str, missing: set[str]) -> str:
    nf = _norm(field)
    return max(missing, key=lambda m: SequenceMatcher(None, nf, _norm(m)).ratio())